#!/bin/bash

echo 'Start to generate README'

_raw_link='https://raw.githubusercontent.com/DaoCloud-Labs/guide-daocloud/master'
_blob_link='https://github.com/DaoCloud-Labs/guide-daocloud/blob/master'
_roots=$(ls)

# Init README
echo '# Guide DaoCloud' > README.md
echo 'Scripts and YAMLs in DaoCloud Guide' >> README.md
echo '> *This document is generated by scripts*<br>' >> README.md
echo '> *Please contact wei.shi@daocloud.io if there is any mistake*' >> README.md

# Get root dirs
for _root in $(ls)
do
    if [[ -d $_root ]]; then
        # List root dir
        echo "  List $_root"
        echo "## $_root" >> README.md
        for _dir in $(ls $_root)
        do
            # There should be yamls/scripts/images dirs in root dir
            if [[ -d ${_root}/${_dir} ]]; then
                echo "    List ${_root}/$_dir"
                echo "#### $_dir" >> README.md
                for _file in $(ls ${_root}/${_dir})
                do
                    # Get file type
                    _file_type=$(echo "$_file" | awk -F '.' '{print $NF}')
                    if [[ "$_file_type" == "md" ]]; then
                        # md is markdown file, generate preview for this type file, link is blob link
                        _file_link="${_blob_link}/${_root}/${_dir}/${_file}"
                        echo "      ${_file}:"
                        echo "        ${_file_link}"
                        echo "- [$_file](${_file_link})" >> README.md
                        # Add 7 lines preview for md file 
                        for i in `seq 1 7`
                        do
                            _file_line=$(sed -n "${i}p" ${_dir}/${_file})
                            echo "  > ${_file_line}" >> README.md
                        done
                    else
                        # other type files' link is raw link
                        _file_link="${_raw_link}/${_root}/${_dir}/${_file}"
                        echo "      ${_file}:"
                        echo "        ${_file_link}"
                        echo "- [$_file](${_file_link})" >> README.md
                    fi
                done
            else
                echo "    Skip $_dir"
            fi
        done
    else
        echo "  Skip $_root"
    fi
done

echo 'Complete to generate README'
